### ISSUE TITLE
Allow custom commit title format

### ISSUE THREAD

**Issue by AmrAbdulrahman** [carloscuesta/gitmoji-cli#1002]
### Description of the problem

Currently, the commit title is hardcoded as following:
```
`${answers.gitmoji} ${scope}${answers.title}`
```

This is **not** flexible and doesn't allow custom formats to meet different team conventions.

### Solution

Allow new config field `commitTitleFormat` that accepts a string with placeholders to be filled out by the cli.

Example usage:

.gitmojirc.json
```
{
  "autoAdd": false,
  "emojiFormat": "emoji" ,
  "scopePrompt": false,
  "gitmojisUrl": "https://gitmoji.dev/api/gitmojis",
  "commitTitleFormat": "{{ticketid}} ({{scope}}): {{gitmoji}} {{title}}",
  "customFields": {    
    "ticketid": {
      "type": "string", // to be passed straight to inquirer
      "message": "Please enter Ticket ID", // to be passed straight to inquirer
      "default": "", // to be passed straight to inquirer
      "choices": ["A", "B"] // to be passed straight to inquirer
    }
  }
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue requesting the same feature.

**Comment by AmrAbdulrahman** [comment]
I am willing to create a MR for that if we agree on the approach @carloscuesta

**Comment by carloscuesta** [comment]
Hey! @AmrAbdulrahman thanks for opening an issue, this is actually very similar to what we discussed in #989 but scoped to the commit title instead of the message

I think we should definitely allow people to customise the way the "templates" are applied, without having to consider every possible use-case in the cli as it can be quite tricky to fit all the needs

I have to say though that the change you're suggesting is a bit against of the "convention" since the idea is to start the commit message prefixed with an emoji. As soon as you add a ticket reference it gets a bit lost

**Comment by AmrAbdulrahman** [comment]
For anyone having the same problem. I decided to better use [commitlint](https://commitlint.js.org/) along with [gitmoji-commit-workflow](https://github.com/arvinxx/gitmoji-commit-workflow/tree/master/packages/commitlint-config) for gitmoji integration.

It's much more flexible with custom formats and plugins, validations, and rules.

**Comment by carloscuesta** [comment]
Sure!!

Thanks for opening the issue 🙌🏻
