### ISSUE TITLE
[rfc] Change of defaults (AutoAdd true -> false / SignedCommit true -> false)

### ISSUE THREAD

**Issue by moseb** [carloscuesta/gitmoji-cli#176]
Hi!

It seems that https://github.com/carloscuesta/gitmoji-cli/blob/775d84b6e48b1943fd04e8d0801b70f0417fcbae/src/gitmoji.js#L21-L24 makes two defaults that I consider troublesome to a general audience:
- `config.setAutoAdd(true)` — because it might make people add and publish secret files by mistake
- `config.setSignedCommit(true)` — because (arguably) most people don't sign their commits with GPG, yet

I can change config for myself — yes — but this ticket is about effect to the general user base.

What do you think?

**Comment by nitaking** [comment]
@moseb
I was thinking exactly the same thing!
I made a version of CLI!

https://github.com/nitaking/gitmoji-c

**Comment by carloscuesta** [comment]
Hey @moseb 

I see the point of this, maybe it's an issue for the users, it's not that bad since it could be disabled.

But I'm concerned about this:

> I can change config for myself — yes — but this ticket is about effect to the general user base.

Maybe the users that are complaining are the ones who don't know how to disable this functionality and the other ones are happy with this behaviour. We have no data to value this. 

But IMHO, we can change it to `false` as a default

**Comment by moseb** [comment]
Cool, please check pull request #195. Thanks!
