### ISSUE TITLE
skip hook if flag `--no-edit`

### ISSUE THREAD

**Issue by ilaborie** [carloscuesta/gitmoji-cli#197]
Hello @carloscuesta!

I'm using the git commit hook installed with `gitmoji -i`

Issue: 

When I amend a commit with the `--no-edit` flag, the hook to create the commit message
I think that the hook shouldn't ask the commit message in this situation

**OS**: MacOS
**gitmoji-cli -v**: 1.9.4
**Node version**: 12.7.0

**Comment by Jeremie-Chauvel** [comment]
Hi @ilaborie,

as gitmoji-cli is using the hook `prepare-commit-msg`, it's [not possible to access git commit arguments](https://git-scm.com/docs/githooks#_prepare_commit_msg). Sadly that means not being able to keep the --no-edit behavior.

We can however detect if we are amending a commit, which means we could prevent the hook from being used in this case.

@carloscuesta This issue is quite old, do you have an opinion ?

**Comment by ilaborie** [comment]
Thanks,
Ok to close the issue without doing anythings,
I'm not sure that the amending detection is a good idea.

**Comment by Jeremie-Chauvel** [comment]
btw you can ctrl-c to pass to hook for faster no-edit
