### ISSUE TITLE
Stuck in Mac Terminal due to using the hook and gitmoji -c

### ISSUE THREAD

**Issue by danicrg** [carloscuesta/gitmoji-cli#223]
Hello @carloscuesta!

I'm using your awesome repo to spice up my commits. But when I use it in Mac Terminal it doesn't get out of the gitmoji -c command. It gets stuck and I need to do ^C.

Issue: 

**OS**: MacOS Mojave
**gitmoji -v**: 2.2.0
**Node version**: 6.9.0

**Comment by carloscuesta** [comment]
Hey @danicrg 

Just tested out with the mac terminal and I am not able to reproduce the error that you say. 

It is possible that you have enabled the signed commit option and this is making that the commit never completes ?

What kind of shell are you using ?

**Comment by danicrg** [comment]
I found that the problem happens because I initialized gitmoji as a commit hook. Then, when using gitmoji -c it gets stuck.

So, to reproduce the problem you should do:

> gitmoji -i
> gitmoji -c

**Comment by ceIia** [comment]
Can confirm, same issue here using `gitmoji -c` after using `gitmoji -i`. MacOS Catalina 10.15.1 -- see attached gif.

![gitmogif](https://user-images.githubusercontent.com/25929147/68248416-11265d80-001d-11ea-93a2-356b0fcbb7bc.gif)

**Comment by carloscuesta** [comment]
Yes that’s because you don’t need to use the hook if you’re going to commit with the client.

The hook is for commiting using git commit as normally you would do. Maybe it’s worth to take a guess about this behaviour

In fact this problem which I weren’t aware of at the moment of writing the issue has been reported by another users previously and the problem was the same the hook.

Not quite sure if it’s a problem of misunderstanding the docs or maybe the docs are not very clear in this aspect

Will see what I can do!

**Comment by carloscuesta** [comment]
As a solution, on #222 I'll implement a check that if you're trying to commit with `gitmoji -c` with the hook file created will point out the issue
