### ISSUE TITLE
Consider a feature to opt out of `git add .`

### ISSUE THREAD

**Issue by sgnl** [carloscuesta/gitmoji-cli#28]
Hello @carloscuesta!

https://github.com/carloscuesta/gitmoji-cli/blob/master/src/gitmoji.js#L99

I'm loving this tool though one thing is really bothering me, it's the fact that when I want to commit gitmoji does a `git add .` and for me I would like to have the option to opt out of this feature either by passing a flag perhaps?

**OS**: OSX 10.11.6
**gitmoji-cli -v**: 1.3.1
**Node version**: `6.9.5` & `7.4.0`

**Comment by carloscuesta** [comment]
Hey @sgnl 

This is a thing I've been considering and I'm thinking to implement a way for configuring the gitmoji-cli, for the things that are done "under the hood" like the `git add .` or the use of unicode instead of the `:emoji` format #14.

Probably, something like `gitmoji --config` that promps and save your preferences into a `.config` file inside of the `~.gitmoji/` directory that now is being used to store the json of gitmojis, a flag could be an easier option but not that handy.

I'm looking the best way to implement this 😄

**Comment by sgnl** [comment]
Oh nice, yeah the config would be a nicer implementation. Thanks for your time

**Comment by wextia** [comment]
That is bothering me too! 

Note that you can create a commit hook with `gitmoji -i` and then execute

`git add path/to/your/file/`

`git commit`

And then you'll be prompted with the `gitmoji` commit screen, but only the files you've added will be commited. I'm aware it is not what you're suggesting, but it's how i do it currently.

**Comment by carloscuesta** [comment]
In the meantime, could work as a workaround @wextia.

**Comment by carloscuesta** [comment]
Done @sgnl @wextia
