### ISSUE TITLE
[Feature request] Additional keyboard commands for selecting emojis

### ISSUE THREAD

**Issue by vhoyer** [carloscuesta/gitmoji-cli#469]
Hello @carloscuesta!

Not a bug report, instead: a feature request :D

What do you think of having the `ctrl+j` be equivalent to `ArrowDown` and `ctrl+k` be equivalent to `ArrowUp`?

This would make the selection of emojis easier (for me at least, that uses primarily vim as the main editor) and it also would function the same as [`fzf`](https://github.com/junegunn/fzf).

**Comment by carloscuesta** [comment]
Hey @vhoyer!

If we can do it easily with Inquirer.js I wouldn't doubt on introducing this. However as I see, there's no option for that aside from arrow keys to navigate through Inquirer prompts, so I would not spend a lot on finding a solution for this, because with the autocomplete and the arrows we are mostly offering a great search experience IMHO!

T

**Comment by vhoyer** [comment]
Oh, I see, I will try adding an issue to inquirer then haha, thank

**Comment by vhoyer** [comment]
Actually, looking at their code, they allow `<Ctrl-n>` and `<Ctrl-p>` to go down and up, which is good enough for me (not great, but good enough haha)
