### ISSUE TITLE
Gitmoji request failed because of raw.githubusercontent.com blocked on some countries

### ISSUE THREAD

**Issue by jalenchuh** [carloscuesta/gitmoji-cli#552]
Hello @carloscuesta!

Issue:

Is it possible to put the `json` file locally?
`https://raw.githubusercontent.com/` was blocked in some areas, so request to `https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json` usually failed.

**OS**: Windows10
**gitmoji -v**: 3.2.18
**Node version**: 15.10.0

**Comment by carloscuesta** [comment]
Yes it's a common error for some users. I'm thinking in a solution that could solve that problem.

Can you access https://gitmoji.dev ?

If you can I might move the file and consume it from the website in order to avoid that on countries that raw github is blocked users can still use this without any problem.

Thanks!

**Comment by carloscuesta** [comment]
This should be fixed at 3.3.0 ❤️

**Comment by jalenchuh** [comment]
Thanks😉

**Comment by jalenchuh** [comment]
I can not update gitmoji-cli to v3.3.0, the newest version I can install is v3.2.18.
And I have seen https://www.npmjs.com/package/gitmoji-cli, the version was still v3.2.18.

**Comment by carloscuesta** [comment]
Published right now! You can install it 😊

**Comment by jalenchuh** [comment]
Thanks! It's so great now. I love it😍

**Comment by carloscuesta** [comment]
Thanks to you too! My mind came to this idea randomly while reading your issue ❤️
