### ISSUE TITLE
Adjust commit title length

### ISSUE THREAD

**Issue by capsuleman** [carloscuesta/gitmoji-cli#682]
Hello @carloscuesta!

Real commit title length should be 50 chars. It should be really calculated according to current gitmoji's length.

Issue:

**OS**:
**gitmoji -v**:
**Node version**:

**Error Message**:

**Comment by carloscuesta** [comment]
Hey! If I'm not mistaken, you're not taking into account the space that is being set between the emoji and the commit title, that's why the value was hardcoded to 48 😅

Also gitmoji.length is not a good way to handle this, because if the user picks the unicode format, the length will be more than 1 but in GitHub the :string: will translate into a single emoji, so I think we can stick with the old approach

Thanks for opening the PR 😊
