### ISSUE TITLE
Feature Request: Support for Sapling

### ISSUE THREAD

**Issue by hacker-DOM** [carloscuesta/gitmoji-cli#968]
### Description of the problem

So I'm playing around with [Sapling](https://sapling-scm.com/) and it looks fantastic; the only thing I'm missing is gitmoji haha

It would be great if Sapling support was added to gitmoji for commiting. 

### Solution

It should't be _that_ difficult, just `sl commit -m MSG` instead of `git commit -m MSG` 🙂

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue requesting the same feature.

**Comment by carloscuesta** [comment]
Hey! 

Thanks for opening the issue, currently I don't see integrating other SCM into the `cli` 😊 

> It should't be that difficult, just sl commit -m MSG instead of git commit -m MSG 🙂

I think you're underestimating a bit the complexity here since we do not only rely on `commit` there are more use cases built-in.

You can always fork the repository and maintain your own version that supports sapling! 🙏🏼 

Have a great day 👋🏼
