### ISSUE TITLE
When writing comments, the text doesn't wrap

### ISSUE THREAD

**Issue by DaniloThiago** [carloscuesta/gitmoji-cli#996]
### Describe the bug

 When writing comments, the text doesn't wrap

### Reproduction

![image](https://user-images.githubusercontent.com/7073492/213526202-38098f15-f537-4e42-b39c-198b47a9fb8b.png)

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 2.81 GB / 15.91 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.55)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji-cli/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji-cli/blob/master/.github/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [ ] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carloscuesta** [comment]
Hey!

Thanks for opening an issue, unfortunately I think this is caused by a downstream dependency see https://github.com/carloscuesta/gitmoji-cli/issues/873 and https://github.com/carloscuesta/gitmoji-cli/issues/93 

I can't reproduce it as I don't own a Windows machine, so feel free to investigate/debug raise a PR if you find something!

Thanks 🙏🏼
